spring.application.name=biblioteca

# Puerto
server.port=8080

# Configuración Base de Datos (PostgreSQL - Railway)
spring.datasource.url=jdbc:postgresql://iriguchi.proxy.rlwy.net:48124/railway
spring.datasource.username=postgres
spring.datasource.password=CJIFEsjgvCoSATOtarkOTkSCMBIDbChL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
